import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";
import { AdminShell } from "../components/layout/AdminShell";
import { peso } from "../lib/format";

export function AddBooking() {
  const navigate=useNavigate();
  const [customers,setCustomers]=useState([]),[inventory,setInventory]=useState([]);
  const [customerId,setCustomerId]=useState(""),[customerSearch,setCustomerSearch]=useState("");
  const [customerMode,setCustomerMode]=useState("new");
  const [customerForm,setCustomerForm]=useState({full_name:"",phone:"",email:"",address:"",city:"",province:"",postal_code:""});
  const [form,setForm]=useState({start_date:"",end_date:"",fulfillment:"delivery",payment_method:"cash",notes:""});
  const [items,setItems]=useState([{item_id:"",quantity:1,delivery_fee_per_piece:0}]);
  const [openSections,setOpenSections]=useState({customer:true,rental:true,items:true,summary:true});
  const [availability,setAvailability]=useState({}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  useEffect(()=>{Promise.all([api("/admin/customers"),api("/admin/inventory")]).then(([c,i])=>{setCustomers(c.customers||[]);setInventory((i.items||[]).filter(x=>x.status==="active"))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  const customer=customers.find(c=>String(c.id)===String(customerId));
  const bookingCustomer=customerMode==="existing"?customer:customerForm;
  const days=form.start_date&&form.end_date?Math.max(1,Math.floor((new Date(form.end_date+"T00:00:00")-new Date(form.start_date+"T00:00:00"))/86400000)+1):1;
  const details=items.map(row=>{const item=inventory.find(x=>String(x.id)===String(row.item_id));const qty=Math.max(0,Number(row.quantity)||0);const rental=Number(item?.daily_price||0)*qty*days;const deposit=Number(item?.security_deposit||0)*qty;const delivery=form.fulfillment==="delivery"?Math.max(0,Number(row.delivery_fee_per_piece)||0)*qty:0;return {...row,item,qty,rental,deposit,delivery,total:rental+deposit+delivery}});
  const totals=details.reduce((a,x)=>({rental:a.rental+x.rental,deposit:a.deposit+x.deposit,delivery:a.delivery+x.delivery,total:a.total+x.total}),{rental:0,deposit:0,delivery:0,total:0});
  const updateItem=(index,key,value)=>setItems(v=>v.map((x,i)=>i===index?{...x,[key]:value}:x));
  const toggleSection=key=>setOpenSections(v=>({...v,[key]:!v[key]}));
  useEffect(()=>{if(!form.start_date||!form.end_date||items.some(x=>!x.item_id||Number(x.quantity)<1)){setAvailability({});return}const timer=setTimeout(()=>api("/admin/availability/check",{method:"POST",body:JSON.stringify({start_date:form.start_date,end_date:form.end_date,items:items.map(x=>({item_id:Number(x.item_id),quantity:Number(x.quantity)}))})}).then(d=>setAvailability(Object.fromEntries(d.items.map(x=>[x.item_id,x])))).catch(()=>setAvailability({})),300);return()=>clearTimeout(timer)},[form.start_date,form.end_date,items]);
  const submit=async e=>{e.preventDefault();setError("");if(customerMode==="existing"&&!customer)return setError("Select an existing customer.");if(customerMode==="new"&&(!customerForm.full_name.trim()||!customerForm.phone.trim()||!customerForm.email.trim()))return setError("Complete the new customer's name, contact number, and email address.");if(form.fulfillment==="delivery"&&!bookingCustomer?.address?.trim())return setError("A complete delivery address is required.");if(form.end_date<form.start_date)return setError("End date cannot be before start date.");if(details.some(x=>!x.item||x.qty<1))return setError("Complete every rental item.");if(new Set(details.map(x=>x.item_id)).size!==details.length)return setError("Add each rental item only once; adjust its quantity instead.");if(details.some(x=>availability[x.item_id]&&!availability[x.item_id].available))return setError("One or more items are unavailable for the selected dates.");setSaving(true);try{const data=await api("/admin/bookings",{method:"POST",body:JSON.stringify({...form,...(customerMode==="new"?customerForm:{}),customer_id:customerMode==="existing"?Number(customerId):null,items:details.map(x=>({item_id:Number(x.item_id),quantity:x.qty,delivery_fee_per_piece:form.fulfillment==="delivery"?Number(x.delivery_fee_per_piece):0}))})});navigate("/admin/bookings",{state:{created:data.booking?.booking_no}})}catch(e){setError(e.message)}finally{setSaving(false)}};
  const matches=customers.filter(c=>!customerSearch||[c.full_name,c.email,c.phone].some(v=>String(v||"").toLowerCase().includes(customerSearch.toLowerCase()))).slice(0,8);
  if(loading)return <AdminShell title="Add Booking" subtitle="Create a new offline booking manually."><div className="admin-card booking-empty-state">Loading customers and inventory…</div></AdminShell>;
  return <AdminShell title="Add Booking" subtitle="Create a new offline booking and enter the customer details manually.">
    <form className="admin-booking-form" onSubmit={submit}>{error&&<div className="login-error">{error}</div>}
      <section className={`admin-card form-section ${openSections.customer?"is-open":"is-collapsed"}`}><button type="button" className="form-section-toggle" onClick={()=>toggleSection("customer")} aria-expanded={openSections.customer}><div className="form-section-title"><span>1</span><div><h2>Customer Information</h2><p>{openSections.customer?"Enter a new walk-in customer or select an existing record.":bookingCustomer?.full_name?`${bookingCustomer.full_name} · ${bookingCustomer.phone}`:"Customer details not completed"}</p></div></div><span className="section-chevron">⌄</span></button>
        {openSections.customer&&<div className="form-section-content">
        <div className="customer-mode-toggle"><button type="button" className={customerMode==="new"?"active":""} onClick={()=>setCustomerMode("new")}>New Customer</button><button type="button" className={customerMode==="existing"?"active":""} onClick={()=>setCustomerMode("existing")}>Existing Customer</button></div>
        {customerMode==="existing"&&<><div className="form-group"><label>Search customer <span className="required">*</span></label><input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="Name, email, or contact number"/></div><div className="customer-picker">{matches.map(c=><button type="button" key={c.id} className={String(c.id)===String(customerId)?"selected":""} onClick={()=>setCustomerId(c.id)}><strong>{c.full_name}</strong><small>{c.email} · {c.phone}</small><span className={`status-pill ${c.status==="active"?"confirmed":"overdue"}`}>{c.status}</span></button>)}</div></>}
        {customerMode==="new"?<div className="customer-information-fields"><div className="form-group"><label>Customer Name <span className="required">*</span></label><input required type="text" value={customerForm.full_name} onChange={e=>setCustomerForm({...customerForm,full_name:e.target.value})} placeholder="Enter full name"/></div><div className="form-group"><label>Contact Number <span className="required">*</span></label><input required type="tel" value={customerForm.phone} onChange={e=>setCustomerForm({...customerForm,phone:e.target.value})} placeholder="09XX XXX XXXX"/></div><div className="form-group"><label>Email Address <span className="required">*</span></label><input required type="email" value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})} placeholder="customer@example.com"/></div><div className="form-group customer-address-field"><label>Full Address <span className="required">*</span></label><textarea required rows="3" value={customerForm.address} onChange={e=>setCustomerForm({...customerForm,address:e.target.value})} placeholder="House number, street, barangay, city, province, postal code"/></div></div>:customer&&<div className="customer-information-fields"><div className="form-group"><label>Customer Name</label><input type="text" readOnly value={customer.full_name||""}/></div><div className="form-group"><label>Contact Number</label><input type="tel" readOnly value={customer.phone||""}/></div><div className="form-group"><label>Email Address</label><input type="email" readOnly value={customer.email||""}/></div><div className="form-group customer-address-field"><label>Full Address</label><textarea rows="3" readOnly value={[customer.address,customer.city,customer.province,customer.postal_code].filter(Boolean).join(", ")}/></div><div className="customer-reference"><small>Customer reference</small><strong>CUST-{String(customer.id).padStart(6,"0")}</strong></div></div>}
        </div>}
      </section>
      <section className={`admin-card form-section ${openSections.rental?"is-open":"is-collapsed"}`}><button type="button" className="form-section-toggle" onClick={()=>toggleSection("rental")} aria-expanded={openSections.rental}><div className="form-section-title"><span>2</span><div><h2>Rental Information</h2><p>{openSections.rental?"Existing duration-based prices are calculated inclusively.":form.start_date&&form.end_date?`${form.start_date} → ${form.end_date} · ${days} days`:"Rental dates not set"}</p></div></div><span className="section-chevron">⌄</span></button>{openSections.rental&&<div className="form-section-content"><div className="form-grid">
        <div className="form-group"><label>Start date <span className="required">*</span></label><input required type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></div>
        <div className="form-group"><label>End date <span className="required">*</span></label><input required type="date" min={form.start_date||undefined} value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></div>
        <div className="form-group"><label>Fulfillment</label><select value={form.fulfillment} onChange={e=>setForm({...form,fulfillment:e.target.value})}><option value="delivery">Delivery</option><option value="pickup">Pickup</option></select></div>
        <div className="form-group"><label>Payment method</label><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="cash">Cash</option><option value="gcash">GCash</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></div>
      </div></div>}</section>
      <section className={`admin-card form-section ${openSections.items?"is-open":"is-collapsed"}`}><button type="button" className="form-section-toggle" onClick={()=>toggleSection("items")} aria-expanded={openSections.items}><div className="form-section-title"><span>3</span><div><h2>Rental Items</h2><p>{openSections.items?"Delivery fees are entered and stored per piece for each item.":`${details.filter(x=>x.item).length} item type${details.filter(x=>x.item).length===1?"":"s"} · ${items.reduce((sum,x)=>sum+(Number(x.quantity)||0),0)} pieces`}</p></div></div><span className="section-chevron">⌄</span></button>{openSections.items&&<div className="form-section-content">
        <div className="admin-booking-items">{details.map((row,index)=><article className="admin-booking-item" key={index}><div className="item-row-head">{row.item?.image_url?<img src={row.item.image_url} alt=""/>:<span className="item-image-placeholder">B</span>}<div className="form-group grow"><label>Rental item <span className="required">*</span></label><select required value={row.item_id} onChange={e=>updateItem(index,"item_id",e.target.value)}><option value="">Select item</option>{inventory.map(x=><option key={x.id} value={x.id}>{x.name} — {peso(Number(x.daily_price))}/day</option>)}</select></div>{items.length>1&&<button type="button" className="mini-button danger" onClick={()=>setItems(v=>v.filter((_,i)=>i!==index))}>Remove</button>}</div>
          <div className="item-input-grid"><div className="form-group"><label>Quantity / pieces</label><input required min="1" step="1" type="number" value={row.quantity} onChange={e=>updateItem(index,"quantity",e.target.value)}/></div><div className="form-group"><label>Rental duration</label><input readOnly value={`${days} day${days===1?"":"s"}`}/></div><div className="form-group"><label>Delivery fee / piece</label><input required min="0" step="0.01" disabled={form.fulfillment!=="delivery"} type="number" value={row.delivery_fee_per_piece} onChange={e=>updateItem(index,"delivery_fee_per_piece",e.target.value)}/></div><div className="form-group"><label>Availability</label><div className={`availability-box ${availability[row.item_id]?.available?"ok":availability[row.item_id]?"bad":""}`}>{availability[row.item_id]?availability[row.item_id].available?`Available (${availability[row.item_id].available_quantity})`:`Only ${availability[row.item_id].available_quantity} available`:"Select dates and item"}</div></div></div>
          <div className="item-calculation"><span>Rental <b>{peso(row.rental)}</b></span><span>Delivery <b>{peso(row.delivery)}</b></span><span>Deposit <b>{peso(row.deposit)}</b></span><span>Item total <b>{peso(row.total)}</b></span></div></article>)}</div>
        <button type="button" className="secondary-button" onClick={()=>setItems(v=>[...v,{item_id:"",quantity:1,delivery_fee_per_piece:0}])}>+ Add another item</button></div>}
      </section>
      <section className={`admin-card form-section booking-review ${openSections.summary?"is-open":"is-collapsed"}`}><button type="button" className="form-section-toggle" onClick={()=>toggleSection("summary")} aria-expanded={openSections.summary}><div className="form-section-title"><span>4</span><div><h2>Booking Summary</h2><p>{openSections.summary?"Review all customer, rental, and fee details before saving.":`Grand total: ${peso(totals.total)}`}</p></div></div><span className="section-chevron">⌄</span></button>{openSections.summary&&<div className="form-section-content booking-review-content"><div className="form-group"><label>Booking notes</label><textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optional internal or delivery notes"/></div><div className="review-total"><div><span>Rental subtotal</span><strong>{peso(totals.rental)}</strong></div><div><span>Security deposit</span><strong>{peso(totals.deposit)}</strong></div><div><span>Total delivery fee</span><strong>{peso(totals.delivery)}</strong></div><div className="grand"><span>Grand total</span><strong>{peso(totals.total)}</strong></div></div></div>}</section>
      <div className="sticky-form-actions"><button type="button" className="secondary-button" onClick={()=>navigate("/admin/bookings")}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Creating booking…":"Create Pending Booking"}</button></div>
    </form>
  </AdminShell>;
}
